<x-layouts.app :title="$instrumento->nombre">
    @php($editable = auth()->user()->can('update', $instrumento))
    <div class="flex flex-col gap-4 xl:flex-row xl:items-start xl:justify-between">
        <div><a href="{{ route('instruments.index') }}" class="text-sm font-semibold text-brand-700">← Versiones</a><div class="mt-3 flex flex-wrap items-center gap-2"><x-ui.badge :variant="match($instrumento->estado->value){'PUBLICADO'=>'success','BORRADOR'=>'warning',default=>'neutral'}">{{ str($instrumento->estado->value)->lower()->headline() }}</x-ui.badge><span class="text-sm font-semibold text-slate-400">Versión {{ $instrumento->version }}</span></div><h1 class="mt-3 max-w-4xl text-2xl font-bold text-navy-900">{{ $instrumento->nombre }}</h1><p class="mt-2 max-w-3xl text-sm/6 text-slate-500">{{ $instrumento->descripcion }}</p></div>
        <div class="flex flex-wrap gap-2">
            @if($editable)<a href="{{ route('admin.instruments.edit', $instrumento) }}" class="app-button-secondary">Datos generales</a><form method="POST" action="{{ route('admin.instruments.publish', $instrumento) }}">@csrf<button class="app-button-primary">Publicar versión</button></form>@endif
            @can('archive', $instrumento)<form method="POST" action="{{ route('admin.instruments.archive', $instrumento) }}" onsubmit="return confirm('¿Archivar esta versión?')">@csrf<button class="app-button-secondary">Archivar</button></form>@endcan
        </div>
    </div>

    @if($errors->any())<x-ui.alert variant="warning" title="Revisa la información" class="mt-6"><ul class="list-inside list-disc">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></x-ui.alert>@endif

    <div class="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <x-ui.card><p class="text-sm text-slate-500">Dominios</p><p class="mt-2 text-3xl font-bold text-navy-900">{{ $instrumento->dominios->count() }}</p></x-ui.card>
        <x-ui.card><p class="text-sm text-slate-500">Criterios</p><p class="mt-2 text-3xl font-bold text-navy-900">{{ $instrumento->dominios->sum(fn($d) => $d->criterios->count()) }}</p></x-ui.card>
        <x-ui.card><p class="text-sm text-slate-500">Descriptores</p><p class="mt-2 text-3xl font-bold text-navy-900">{{ $instrumento->dominios->sum(fn($d) => $d->criterios->sum(fn($c) => $c->descriptores->count())) }}</p></x-ui.card>
        <x-ui.card><p class="text-sm text-slate-500">Peso acumulado</p><p class="mt-2 text-3xl font-bold {{ (float)$instrumento->dominios->sum('peso') === 100.0 ? 'text-emerald-700' : 'text-amber-700' }}">{{ number_format($instrumento->dominios->sum('peso'), 2) }} %</p></x-ui.card>
    </div>

    @can('replicate', $instrumento)
    <x-ui.card class="mt-6 border-brand-200 bg-brand-50/40"><div class="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><h2 class="font-bold text-navy-900">Crear una nueva versión editable</h2><p class="mt-1 text-sm text-slate-500">Se copiarán dominios, criterios, descriptores y categorías.</p></div><form method="POST" action="{{ route('admin.instruments.duplicate', $instrumento) }}" class="flex gap-2">@csrf<input name="version" required placeholder="Ej. 2.0" class="min-h-11 w-32 rounded-xl border border-slate-300 px-3 text-sm"><button class="app-button-primary">Duplicar</button></form></div></x-ui.card>
    @endcan

    <div class="mt-8 flex items-center justify-between"><div><h2 class="text-xl font-bold text-navy-900">Estructura jerárquica</h2><p class="mt-1 text-sm text-slate-500">Dominios, criterios y descriptores calificables.</p></div></div>

    <div class="mt-4 space-y-5">
    @forelse($instrumento->dominios as $domain)
        <section class="app-card overflow-hidden">
            <div class="border-b border-slate-100 bg-navy-950 px-5 py-4 text-white md:px-6"><div class="flex flex-wrap items-start justify-between gap-3"><div><p class="text-xs font-bold uppercase tracking-wider text-brand-300">{{ $domain->codigo }} · {{ number_format($domain->peso, 2) }} %</p><h3 class="mt-1 text-lg font-bold">{{ $domain->nombre }}</h3></div>@if(!$domain->activo)<x-ui.badge variant="warning">Inactivo</x-ui.badge>@endif</div></div>
            <div class="space-y-4 p-4 md:p-6">
                @if($editable)<details class="rounded-xl border border-slate-200 p-4"><summary class="cursor-pointer text-sm font-semibold text-brand-700">Editar dominio</summary><form method="POST" action="{{ route('admin.instruments.domains.update', [$instrumento,$domain]) }}" class="mt-4 grid gap-3 md:grid-cols-4">@csrf @method('PUT')<input name="codigo" value="{{ $domain->codigo }}" required class="rounded-xl border border-slate-300 p-2.5 text-sm" placeholder="Código"><input name="nombre" value="{{ $domain->nombre }}" required class="rounded-xl border border-slate-300 p-2.5 text-sm md:col-span-2" placeholder="Nombre"><input name="peso" type="number" step="0.01" value="{{ $domain->peso }}" required class="rounded-xl border border-slate-300 p-2.5 text-sm"><input name="orden" type="number" value="{{ $domain->orden }}" required class="rounded-xl border border-slate-300 p-2.5 text-sm"><label class="flex items-center gap-2 text-sm"><input type="hidden" name="activo" value="0"><input type="checkbox" name="activo" value="1" @checked($domain->activo)> Activo</label><div class="flex gap-2 md:col-span-2 md:justify-end"><button class="app-button-secondary">Guardar dominio</button></div></form><form method="POST" action="{{ route('admin.instruments.domains.destroy', [$instrumento,$domain]) }}" class="mt-3 text-right" onsubmit="return confirm('¿Eliminar el dominio y toda su estructura?')">@csrf @method('DELETE')<button class="text-sm font-semibold text-red-600">Eliminar dominio</button></form></details>@endif

                @foreach($domain->criterios as $criterion)
                    <details open class="rounded-2xl border border-slate-200"><summary class="cursor-pointer list-none px-4 py-4 md:px-5"><div class="flex items-center justify-between gap-3"><div><span class="text-xs font-bold text-brand-700">Criterio {{ $criterion->codigo }}</span><h4 class="mt-1 font-bold text-slate-800">{{ $criterion->nombre }}</h4></div><x-ui.badge>{{ $criterion->descriptores->count() }} descriptores</x-ui.badge></div></summary>
                    <div class="border-t border-slate-100 p-4 md:p-5">
                        @if($editable)<form method="POST" action="{{ route('admin.instruments.criteria.update', [$instrumento,$domain,$criterion]) }}" class="mb-2 grid gap-2 rounded-xl bg-slate-50 p-3 md:grid-cols-5">@csrf @method('PUT')<input name="codigo" value="{{ $criterion->codigo }}" required class="rounded-lg border border-slate-300 p-2 text-sm"><input name="nombre" value="{{ $criterion->nombre }}" required class="rounded-lg border border-slate-300 p-2 text-sm md:col-span-2"><input name="orden" type="number" value="{{ $criterion->orden }}" required class="rounded-lg border border-slate-300 p-2 text-sm"><input type="hidden" name="activo" value="{{ $criterion->activo ? 1 : 0 }}"><button class="app-button-secondary min-h-9 py-1">Actualizar</button></form><form method="POST" action="{{ route('admin.instruments.criteria.destroy', [$instrumento,$domain,$criterion]) }}" class="mb-4 text-right" onsubmit="return confirm('¿Eliminar este criterio y sus descriptores?')">@csrf @method('DELETE')<button class="text-xs font-semibold text-red-600">Eliminar criterio</button></form>@endif
                        <ol class="space-y-2">@foreach($criterion->descriptores as $descriptor)<li class="rounded-xl border border-slate-100 bg-white p-3"><div class="flex gap-3"><span class="grid size-8 shrink-0 place-items-center rounded-lg bg-brand-50 text-xs font-bold text-brand-800">{{ $descriptor->codigo }}</span><p class="flex-1 text-sm/6 text-slate-600">{{ $descriptor->descripcion }}</p><x-ui.badge variant="info">0 · 1 · 2</x-ui.badge></div>@if($editable)<details class="mt-2 pl-11"><summary class="cursor-pointer text-xs font-semibold text-brand-700">Editar descriptor</summary><form method="POST" action="{{ route('admin.instruments.descriptors.update', [$instrumento,$criterion,$descriptor]) }}" class="mt-2 grid gap-2 md:grid-cols-6">@csrf @method('PUT')<input name="codigo" value="{{ $descriptor->codigo }}" required class="rounded-lg border border-slate-300 p-2 text-sm"><textarea name="descripcion" required class="rounded-lg border border-slate-300 p-2 text-sm md:col-span-3">{{ $descriptor->descripcion }}</textarea><input name="orden" type="number" value="{{ $descriptor->orden }}" required class="rounded-lg border border-slate-300 p-2 text-sm"><input type="hidden" name="activo" value="{{ $descriptor->activo ? 1 : 0 }}"><button class="app-button-secondary min-h-9 py-1">Guardar</button></form></details>@endif</li>@endforeach</ol>
                        @if($editable)<details class="mt-4 rounded-xl border border-dashed border-brand-300 p-3"><summary class="cursor-pointer text-sm font-semibold text-brand-700">+ Agregar descriptor</summary><form method="POST" action="{{ route('admin.instruments.descriptors.store', [$instrumento,$criterion]) }}" class="mt-3 grid gap-2 md:grid-cols-6">@csrf<input name="codigo" required placeholder="Código" class="rounded-lg border border-slate-300 p-2 text-sm"><textarea name="descripcion" required placeholder="Descripción evaluable" class="rounded-lg border border-slate-300 p-2 text-sm md:col-span-3"></textarea><input name="orden" type="number" min="1" required placeholder="Orden" class="rounded-lg border border-slate-300 p-2 text-sm"><input type="hidden" name="activo" value="1"><button class="app-button-primary min-h-9 py-1">Agregar</button></form></details>@endif
                    </div></details>
                @endforeach
                @if($editable)<details class="rounded-xl border border-dashed border-brand-300 p-4"><summary class="cursor-pointer text-sm font-semibold text-brand-700">+ Agregar criterio</summary><form method="POST" action="{{ route('admin.instruments.criteria.store', [$instrumento,$domain]) }}" class="mt-3 grid gap-2 md:grid-cols-5">@csrf<input name="codigo" required placeholder="Código" class="rounded-lg border border-slate-300 p-2 text-sm"><input name="nombre" required placeholder="Nombre" class="rounded-lg border border-slate-300 p-2 text-sm md:col-span-2"><input name="orden" type="number" min="1" required placeholder="Orden" class="rounded-lg border border-slate-300 p-2 text-sm"><input type="hidden" name="activo" value="1"><button class="app-button-primary min-h-9 py-1">Agregar</button></form></details>@endif
            </div>
        </section>
    @empty<x-ui.card><p class="py-6 text-center text-slate-500">Esta versión todavía no tiene dominios.</p></x-ui.card>@endforelse
    </div>

    @if($editable)<details class="app-card mt-5 p-5"><summary class="cursor-pointer font-bold text-brand-700">+ Agregar dominio</summary><form method="POST" action="{{ route('admin.instruments.domains.store', $instrumento) }}" class="mt-4 grid gap-3 md:grid-cols-5">@csrf<input name="codigo" required placeholder="Código" class="rounded-xl border border-slate-300 p-2.5 text-sm"><input name="nombre" required placeholder="Nombre" class="rounded-xl border border-slate-300 p-2.5 text-sm md:col-span-2"><input name="peso" type="number" step="0.01" min="0.01" max="100" required placeholder="Peso %" class="rounded-xl border border-slate-300 p-2.5 text-sm"><input name="orden" type="number" min="1" required placeholder="Orden" class="rounded-xl border border-slate-300 p-2.5 text-sm"><input type="hidden" name="activo" value="1"><button class="app-button-primary md:col-start-5">Agregar</button></form></details>@endif

    <div class="mt-8 grid gap-6 xl:grid-cols-[1fr_22rem]">
        <x-ui.card><h2 class="text-lg font-bold text-navy-900">Categorías de resultado</h2><div class="mt-4 space-y-3">@foreach($instrumento->categoriasResultado as $category)<div class="rounded-xl border border-slate-200 p-4"><div class="flex flex-wrap justify-between gap-2"><p class="font-semibold text-slate-800">{{ $category->nombre }}</p><x-ui.badge>{{ $category->porcentaje_desde }} % – {{ $category->porcentaje_hasta }} %</x-ui.badge></div><p class="mt-2 text-sm text-slate-500">{{ $category->interpretacion }}</p>@if($editable)<details class="mt-3"><summary class="cursor-pointer text-xs font-semibold text-brand-700">Editar categoría</summary><form method="POST" action="{{ route('admin.instruments.categories.update',[$instrumento,$category]) }}" class="mt-2 grid gap-2 md:grid-cols-5">@csrf @method('PUT')<input name="nombre" value="{{ $category->nombre }}" required class="rounded-lg border border-slate-300 p-2 text-sm"><input name="porcentaje_desde" type="number" step="0.01" value="{{ $category->porcentaje_desde }}" required class="rounded-lg border border-slate-300 p-2 text-sm"><input name="porcentaje_hasta" type="number" step="0.01" value="{{ $category->porcentaje_hasta }}" required class="rounded-lg border border-slate-300 p-2 text-sm"><input name="orden" type="number" value="{{ $category->orden }}" required class="rounded-lg border border-slate-300 p-2 text-sm"><input name="interpretacion" value="{{ $category->interpretacion }}" class="rounded-lg border border-slate-300 p-2 text-sm md:col-span-4"><button class="app-button-secondary min-h-9 py-1">Guardar</button></form><form method="POST" action="{{ route('admin.instruments.categories.destroy',[$instrumento,$category]) }}" class="mt-2 text-right" onsubmit="return confirm('¿Eliminar esta categoría?')">@csrf @method('DELETE')<button class="text-xs font-semibold text-red-600">Eliminar categoría</button></form></details>@endif</div>@endforeach</div>
        @if($editable)<details class="mt-4 rounded-xl border border-dashed border-brand-300 p-3"><summary class="cursor-pointer text-sm font-semibold text-brand-700">+ Agregar categoría</summary><form method="POST" action="{{ route('admin.instruments.categories.store',$instrumento) }}" class="mt-3 grid gap-2 md:grid-cols-5">@csrf<input name="nombre" required placeholder="Nombre" class="rounded-lg border border-slate-300 p-2 text-sm"><input name="porcentaje_desde" type="number" step="0.01" required placeholder="Desde" class="rounded-lg border border-slate-300 p-2 text-sm"><input name="porcentaje_hasta" type="number" step="0.01" required placeholder="Hasta" class="rounded-lg border border-slate-300 p-2 text-sm"><input name="orden" type="number" required placeholder="Orden" class="rounded-lg border border-slate-300 p-2 text-sm"><input name="interpretacion" placeholder="Interpretación" class="rounded-lg border border-slate-300 p-2 text-sm md:col-span-4"><button class="app-button-primary min-h-9 py-1">Agregar</button></form></details>@endif</x-ui.card>
        <x-ui.card><h2 class="text-lg font-bold text-navy-900">Escala oficial</h2><div class="mt-4 space-y-3">@foreach([[0,'No cumple','bg-red-50 text-red-700'],[1,'Cumple parcialmente','bg-amber-50 text-amber-700'],[2,'Cumple','bg-emerald-50 text-emerald-700']] as [$score,$label,$classes])<div class="flex items-center gap-3"><span class="grid size-10 place-items-center rounded-xl font-bold {{ $classes }}">{{ $score }}</span><span class="text-sm font-semibold text-slate-700">{{ $label }}</span></div>@endforeach</div></x-ui.card>
    </div>
</x-layouts.app>
