@php($evaluacion = $evaluacion ?? null)
@php($editing = $evaluacion !== null)
@php($assignedResponsibles = old('responsables', $editing ? $evaluacion->dominios->pluck('responsable_id','dominio_id')->all() : []))
@php($assignedEvaluators = old('evaluadores', $editing ? $evaluacion->evaluadores->pluck('id')->all() : []))
<div class="grid gap-5 md:grid-cols-2">
    <x-ui.form-field label="Código" name="codigo" :value="$evaluacion->codigo ?? null" required placeholder="Ej. EVAL-2026-001" />
    <x-ui.form-field label="Nombre del proceso" name="nombre" :value="$evaluacion->nombre ?? null" required />
    <div><label class="mb-1.5 block text-sm font-semibold text-slate-700">Tipo de escenario</label><select name="tipo_escenario" required class="min-h-11 w-full rounded-xl border border-slate-300 px-3 text-sm">@foreach(App\Enums\TipoEscenario::cases() as $type)<option value="{{ $type->value }}" @selected(old('tipo_escenario',$evaluacion->tipo_escenario->value ?? '')===$type->value)>{{ str($type->value)->lower()->headline() }}</option>@endforeach</select></div>
    <div><label class="mb-1.5 block text-sm font-semibold text-slate-700">Instrumento</label><input value="{{ $selectedModel->nombre }} · v{{ $selectedModel->version }}" disabled class="min-h-11 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm"><input type="hidden" name="modelo_evaluacion_id" value="{{ $selectedModel->id }}"></div>
    <x-ui.form-field label="Fecha de inicio" name="fecha_inicio" type="date" :value="$evaluacion?->fecha_inicio?->format('Y-m-d')" required />
    <x-ui.form-field label="Límite de carga" name="fecha_limite_carga" type="date" :value="$evaluacion?->fecha_limite_carga?->format('Y-m-d')" required />
    <x-ui.form-field label="Inicio de evaluación" name="fecha_inicio_evaluacion" type="date" :value="$evaluacion?->fecha_inicio_evaluacion?->format('Y-m-d')" />
    <x-ui.form-field label="Cierre previsto" name="fecha_cierre_prevista" type="date" :value="$evaluacion?->fecha_cierre_prevista?->format('Y-m-d')" />
</div>
<div class="mt-5"><label class="mb-1.5 block text-sm font-semibold text-slate-700">Descripción</label><textarea name="descripcion" rows="4" class="w-full rounded-xl border border-slate-300 p-3 text-sm">{{ old('descripcion',$evaluacion->descripcion ?? '') }}</textarea></div>
<div class="mt-7"><h2 class="text-lg font-bold text-navy-900">Responsables por dominio</h2><p class="mt-1 text-sm text-slate-500">Una misma persona puede responsabilizarse de más de un dominio.</p><div class="mt-4 grid gap-3 md:grid-cols-2">@foreach($selectedModel->dominios as $domain)<label class="rounded-xl border border-slate-200 p-4"><span class="block text-xs font-bold text-brand-700">{{ $domain->codigo }} · {{ $domain->peso }} %</span><span class="mt-1 block text-sm font-semibold text-slate-800">{{ $domain->nombre }}</span><select name="responsables[{{ $domain->id }}]" required class="mt-3 min-h-11 w-full rounded-xl border border-slate-300 px-3 text-sm"><option value="">Seleccionar responsable</option>@foreach($responsibles as $user)<option value="{{ $user->id }}" @selected(($assignedResponsibles[$domain->id] ?? null)==$user->id)>{{ $user->name }}</option>@endforeach</select></label>@endforeach</div>@error('responsables')<p class="mt-2 text-sm text-red-600">{{ $message }}</p>@enderror</div>
<div class="mt-7"><h2 class="text-lg font-bold text-navy-900">Evaluadores</h2><p class="mt-1 text-sm text-slate-500">El primer evaluador seleccionado se registra como principal.</p><div class="mt-4 grid gap-3 md:grid-cols-2">@foreach($evaluators as $user)<label class="flex items-center gap-3 rounded-xl border border-slate-200 p-4"><input type="checkbox" name="evaluadores[]" value="{{ $user->id }}" @checked(in_array($user->id,$assignedEvaluators)) class="size-4 rounded border-slate-300 text-navy-900"><span><span class="block text-sm font-semibold text-slate-800">{{ $user->name }}</span><span class="block text-xs text-slate-500">{{ $user->email }}</span></span></label>@endforeach</div>@error('evaluadores')<p class="mt-2 text-sm text-red-600">{{ $message }}</p>@enderror</div>
